# Change these first
owner: Herbafill-HFG # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: YouTube
    url: https://youtube.com
  - name: Orrdugi
    url: https://orrdugulasellen.hu
  - name: Herbafill
    url: https://herbafill.hu
  - name: Reflux - Hu
    url: https://refluxparna.hu
  - name: Gegen
    url: https://gegenverstopftenase.de
  - name: Reflux - De
    url: https://refluxkissen.de
  - name: Beistress - De
    url: https://beistress.de
  - name: Oreiller - Fr
    url: https://oreillerreflux.fr
  - name: Herbafill.Eu
    url: https://herbafill.eu
  

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status/
  logoUrl: https://raw.githubusercontent.com/Herbafill-HFG/status/master/static/img/icon.svg
  name: Monitoring - Herbafill Services
  introTitle: "**HFG Web Monitoring** ."
  introMessage: HFG web assests **real-time** data from our github. [**HFG**](https://herbafill.group)
  navbar:
    - title: Status
      href: /status/
    - title: HFG Status
      href: https://github.com/$OWNER/$REPO/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
