# Change these first
owner: Herbafill-HFG # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: YouTube
    url: https://youtube.com
  - name: Orrdugi
    url: https://orrdugulasellen.hu
  - name: Google News
    url: https://www.news.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Herbafill
    url: https://herbafill.hu
    - name: Reflux - Hu
    url: https://refluxparna.hu

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status/
  logoUrl: https://raw.githubusercontent.com/Herbafill-HFG/status/master/static/img/icon.svg
  name: Upptime - Herbafill Services
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a  status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /status/
    - title: HFG Status
      href: https://github.com/$OWNER/$REPO/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
